CREATE DATABASE wildlife;
USE wildlife;

CREATE TABLE sightings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    location VARCHAR(255) NOT NULL,
    species VARCHAR(255) NOT NULL,
    count INT NOT NULL,
    image VARCHAR(255),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
